### ISSUE TITLE
Consider listing out allowed regions in readme

### ISSUE THREAD

**Issue by puicchan** [Azure-Samples/apptemplate-wordpress-on-aca#4]
Saw the allowed regions in main.bicep, for azd, it may be good to list the allowed regions out in the readme. The first time I tried deploying this template using azd, deployment failed. Think it was because I picked a region that is not supported by ACA.

**Comment by kpantos** [comment]
The allowed regions were reduced to the ones allowed when deploying ACA from the portal to ensure that the service is available at the region specified.

Having said that there's a chance of the deployment failing because of other reasons like capacity issues or because the rest of the services (MariaDB) might not be available in the selected region.

So, it is difficult to document out in which region the deployment will eventually succeed.

**Comment by puicchan** [comment]
@jongio, I don't think azd is currently restricting the region based on what's in Bicep. Perhaps a feature we should support in azd? Thoughts?

**Comment by kpantos** [comment]
It sort of does by respecting (throwing an error), the main bicep allowed values attribute of the location parameter.

**Comment by puicchan** [comment]
I just tried and hit this error: 
```

ERROR: deployment failed: error deploying infrastructure: failed deploying: deploying to subscription:

Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'jumphost-deployment' is not valid according to the validation procedure. The tracking id is '66de4801-dd0f-45b9-abcd-b5bcb557112a'. See inner errors for details.
SkuNotAvailable: The requested VM size for resource 'Following SKUs have failed for Capacity Restrictions: Standard_F4s_v2' is currently not available in location 'westus'. Please try another size or deploy to a different location or different zone. See https://aka.ms/azureskunotavailable for details.
```

**Comment by kpantos** [comment]
Unfortunately, that's because of regional Capacity Restrictions.
To resolve this issue, you will either have to:
- Change the jumphost sku at modules/jumphost.bicep
- Deploy without a jumphost by setting a param at main.parameters.json
  ```
     "deployJumpHost": {
        "value": false
      }
  ```
- Deploy to a different region where there are no capacity issues
